### PR TITLE
fix: add llm retry check

### LINKED ISSUE #170: Migrate `checkLlmRetryableState()`
Use this migrated shared method across all plugins with custom implementations. 

Learn from all the plugin implementations to make the best version of this method. 

> I guess it would be ideal to migrate this into our SDK instead.

_Originally posted by @0x4007 in https://github.com/ubiquity-os-marketplace/text-conversation-rewards/pull/469#discussion_r2675018582_

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves https://github.com/ubiquity-os/plugin-sdk/issues/170

### CODE REVIEW

File: src/pull-request-task-matcher/pull-request-commenter.ts [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+        owner: pr.owner,
+        repo: pr.repo,
+        comment_id: existing.id,
+        body: this._context.commentHandler.createCommentBody(this._context, this._context.logger.info(body), { raw: true }),
+      });
+      return;
+    }
+
+    await this._context.commentHandler.postComment(this._context, this._context.logger.info(body), { raw: true });
+  }
```
[the remark this answers is not in the document]
Comment (gentlementlegen) [reply src/pull-request-task-matcher/pull-request-commenter.ts:34]: Untrue, the logger returns and object

File: src/pull-request-task-matcher/llm-issue-matcher.ts [hunk 2]
```diff
@@ -16,6 +16,8 @@ const MAX_TOTAL_ISSUES_FACTOR = 3;
 
 const RETRYABLE_HTTP_STATUS = new Set([408, 409, 425, 429, 500, 502, 503, 504]);
 const RETRYABLE_ERROR_CODE = new Set(["ETIMEDOUT", "ECONNRESET", "EAI_AGAIN"]);
+const NON_RETRYABLE_MESSAGE_FRAGMENTS = ["missing openrouter_api_key", "missing ubiquitykerneltoken", "kernel attestation"];
+const RETRYABLE_MESSAGE_FRAGMENTS = ["invalid json", "empty llm response"];
```
Comment (0x4007) [inline src/pull-request-task-matcher/llm-issue-matcher.ts]: What is it parsing? I tend to avoid LLM logic that depends on keyword matching but if this is in headers and not from LLM output it can potentially be ok.

File: src/pull-request-task-matcher/llm-issue-matcher.ts [hunk 3]
```diff
@@ -101,13 +103,17 @@ export class LlmIssueMatcher {
...
-            .map((s) => ({
-              owner: s.owner,
-              repo: s.repo,
-              number: s.number,
-              confidence: this._clamp01(s.confidence),
-              reason: s.reason,
-            }))
+            .map((s) => {
+              const number = Number(s.number);
+              const confidence = this._clamp01(Number(s.confidence));
```
Comment (0x4007) [inline src/pull-request-task-matcher/llm-issue-matcher.ts]: Confidence isn't reliable from LLMs so another thing I avoid here, unless you're using something like vector embeddings and cosine functions...

**Review by 0x4007 — CHANGES_REQUESTED** [review]
It's a lot of code changes again, but a common poor implementation I've seen from many LLMs is this idea of deriving "confidence" and keyword parsing. LLMs are NOT good with numbers intrinsically. Using external tools like programming languages is fine but not deriving a "confidence" score directly from the LLM.

File: src/pull-request-task-matcher/llm-issue-matcher.ts (hunk 3 above)
Comment (gentlementlegen) [reply src/pull-request-task-matcher/llm-issue-matcher.ts]: This is AI slop I'll revert it

**Comment by gentlementlegen** [comment]
@0x4007 Agreed, it's just that vector embeddings are not good with code, we should do longer research on what algorithms are good for vectoring it maybe like BM25 or so. Probably should be its own task.

File: src/pull-request-task-matcher/llm-issue-matcher.ts (hunk 2 above)
Comment (gentlementlegen) [reply src/pull-request-task-matcher/llm-issue-matcher.ts]: Was old code checks that can be removed (handled in SDK) c113237852537f95b1f2f02201df195adf7dee17

**Comment by 0x4007** [comment]
> @0x4007 Agreed, it's just that vector embeddings are not good with code, we should do longer research on what algorithms are good for vectoring it maybe like BM25 or so. Probably should be its own task.

I've experimented with simpler scoring models like using true and false to identify features. Then you can easily count the amount of truths and falses to derive a score.
